# Generated by Django 4.2.4 on 2023-08-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=64)),
                ("lastname", models.CharField(max_length=64)),
                ("username", models.CharField(max_length=64, unique=True)),
                ("email", models.EmailField(max_length=64, unique=True)),
                ("password", models.CharField(max_length=64)),
            ],
        ),
    ]
