# Generated by Django 4.2.4 on 2023-08-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_team_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="team_name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
