# Generated by Django 4.1.7 on 2023-08-25 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0011_remove_user_in_team_remove_user_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="member1",
        ),
        migrations.RemoveField(
            model_name="team",
            name="member2",
        ),
        migrations.RemoveField(
            model_name="team",
            name="member3",
        ),
        migrations.RemoveField(
            model_name="team",
            name="member4",
        ),
        migrations.RemoveField(
            model_name="team",
            name="submission",
        ),
        migrations.CreateModel(
            name="UserStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_team", models.BooleanField(default=False)),
                (
                    "joined_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="joined_team",
                        to="portal.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
