# Generated by Django 4.2.7 on 2023-12-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_team_members_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members_count',
            field=models.IntegerField(default=0),
        ),
    ]
